name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2
    - name: Build (mvn package)
      run: mvn -B package --file com.eclipsesource.megit.parent/pom.xml
    - uses: actions/upload-artifact@v4
      with:
        path: ./com.eclipsesource.megit.product/target/products/megit-*-linux.gtk.x86_64.tar.gz
        name: megit-${{ github.run_id }}-linux.gtk.x86_64.tar.gz
    - uses: actions/upload-artifact@v4
      with:
        path: ./com.eclipsesource.megit.product/target/products/megit-*-win32.win32.x86_64.zip
        name: megit-${{ github.run_id }}-win32.win32.x86_64.zip
