name: Draft Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java and Maven
      uses: s4u/setup-maven-action@v1.11.0
      with:
        java-version: 17
        maven-version: 3.9.2
    - name: Build (mvn package)
      run: mvn -B package --file com.eclipsesource.megit.parent/pom.xml
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ./com.eclipsesource.megit.product/target/products/*.zip
