name: Draft Release

on:
  release:
    types: [drafted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build (mvn package)
      run: mvn -B package --file com.eclipsesource.megit.parent/pom.xml
    - name: Upload each zip file as a separate asset
      run: |
        for zipfile in ./com.eclipsesource.megit.product/target/products/*.zip; do
          asset_name=$(basename $zipfile)
          echo "Uploading $asset_name"
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: $(file -b --mime-type $zipfile)" \
            --data-binary @$zipfile \
            ${{ github.event.release.upload_url }}?name=$asset_name
        done
